config/routes.rb
  Rails.application.routes.draw do

  get 'charts/index'
    resources :patients
    root 'patients#index'
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ApplicationRecord
  def self.search(query)
    where("patient_id LIKE ? OR age LIKE ? OR gender LIKE ? OR tumor_type LIKE ? OR tumor_grade LIKE ? OR tumor_location LIKE ? OR treatment LIKE ? OR treatment_outcome LIKE ? OR time_to_recurrence LIKE ? OR recurrence_site LIKE ? OR survival_time LIKE ?",
          "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charts_controller.rb
# app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def index
    @patients = Patient.all

    respond_to do |format|
      format.html
      format.json { render json: @patients }
    end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  def index

    if params[:search].present?
      @patients = Patient.search(params[:search]).page(params[:page]).per(10)
    else
      @patients = Patient.page(params[:page]).per(20)
    end
  end

  # GET /patients/1
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  def create
    @patient = Patient.new(patient_params)

    if @patient.save
      redirect_to @patient, notice: 'Patient was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /patients/1
  def update
    if @patient.update(patient_params)
      redirect_to @patient, notice: 'Patient was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /patients/1
  def destroy
    @patient.destroy
    redirect_to patients_url, notice: 'Patient was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_patient
    @patient = Patient.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def patient_params
    params.require(:patient).permit(:patient_id, :age, :gender, :tumor_type, :tumor_grade, :tumor_location, :treatment, :treatment_outcome, :time_to_recurrence, :recurrence_site, :survival_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/charts/index.html.erb
<!-- app/views/charts/index.html.erb -->
<div class="container mt-4 mb-4">
<h1>Interactive Patient Data Chart</h1>

<%= form_with url: charts_index_path, method: :get, local: true, id: "chartForm" do |form| %>
  <div class="field">
    <%= form.label :x_field, "Select X Axis Field" %>
    <%= form.select :x_field, options_for_select(['age', 'gender', 'tumor_type', 'tumor_grade', 'tumor_location', 'treatment', 'treatment_outcome', 'time_to_recurrence', 'recurrence_site', 'survival_time'], params[:x_field]), {}, { id: 'xField' } %>
  </div>
  <div class="field">
    <%= form.label :y_field, "Select Y Axis Field" %>
    <%= form.select :y_field, options_for_select(['age', 'gender', 'tumor_type', 'tumor_grade', 'tumor_location', 'treatment', 'treatment_outcome', 'time_to_recurrence', 'recurrence_site', 'survival_time'], params[:y_field]), {}, { id: 'yField' } %>
  </div>
  <div class="actions">
    <%= form.submit "Generate Chart", class: "btn btn-primary" %>
  </div>
<% end %>

<canvas id="patientChart" width="600" height="400"></canvas>


<%= javascript_include_tag 'chart_options' %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Brain Tumor", root_path, class: "navbar-brand" %>
    </div>
    <%= link_to "Graphic", charts_index_path, class: "navbar-brand" %>

    <ul class="nav navbar-nav navbar-right">
      <%= form_tag(patients_path, method: :get, class: "form-inline my-2 my-lg-0") do %>
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      <% end %>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>Brain tumor</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    </head>

    <body>

    <%= render 'layouts/nav' %>

    <%= yield %>

  </body>
</html>

app/views/patients/_form.html.erb
<!-- app/views/patients/_form.html.erb -->

<%= form_with(model: patient, local: true) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :patient_id %>
    <%= form.number_field :patient_id, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :tumor_type %>
    <%= form.text_field :tumor_type, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :tumor_grade %>
    <%= form.text_field :tumor_grade, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :tumor_location %>
    <%= form.text_field :tumor_location, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :treatment %>
    <%= form.text_field :treatment, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :treatment_outcome %>
    <%= form.text_field :treatment_outcome, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :time_to_recurrence %>
    <%= form.number_field :time_to_recurrence, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :recurrence_site %>
    <%= form.text_field :recurrence_site, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :survival_time %>
    <%= form.number_field :survival_time, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Guardar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<!-- app/views/patients/edit.html.erb -->

<h1>Editar Paciente</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Cancelar', patient_path(@patient), class: 'btn btn-secondary' %>

app/views/patients/index.html.erb
<div class="container mt-4 mb-4">
<table class="blueTable">
  <thead>
  <tr>
    <th class="text-center">Patient ID</th>
    <th class="text-center">Age</th>
    <th class="text-center">Gender</th>
    <th class="text-center">Tumor Type</th>
    <th class="text-center">Tumor Grade</th>
    <th class="text-center">Tumor Location</th>
    <th class="text-center">Treatment</th>
    <th class="text-center">Treatment Outcome</th>
    <th class="text-center">Time to Recurrence (month)</th>
    <th class="text-center">Recurrence Site</th>
    <th class="text-center">Survival Time (month)</th>
    <th class="text-center" colspan="3"></th>
  </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td class="text-center"><%= patient.patient_id %></td>
        <td class="text-center"><%= patient.age %></td>
        <td class="text-center"><%= patient.gender %></td>
        <td class="text-center"><%= patient.tumor_type %></td>
        <td class="text-center"><%= patient.tumor_grade %></td>
        <td class="text-center"><%= patient.tumor_location %></td>
        <td class="text-center"><%= patient.treatment %></td>
        <td class="text-center"><%= patient.treatment_outcome %></td>
        <td class="text-center"><%= patient.time_to_recurrence %></td>
        <td class="text-center"><%= patient.recurrence_site %></td>
        <td class="text-center"><%= patient.survival_time %></td>
      </tr>
    <% end %>
  </tbody>

  <tfoot>
  <tr>
    <td colspan="11">
      <div class="links">
        <%= paginate @patients %>
      </div>


    </td>
  </tr>
  </tfoot>
</table>
</div>

app/views/patients/new.html.erb
<!-- app/views/patients/new.html.erb -->

<h1>Agregar Nuevo Paciente</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Cancelar', patients_path, class: 'btn btn-secondary' %>

app/views/patients/show.html.erb
<!-- app/views/patients/show.html.erb -->
<div class="col-md-6 col-md-offset-3">
  <div class="container mt-4 mb-4">
    <h1>Detalles del Paciente</h1>

    <p><strong>Patient ID:</strong> <%= @patient.patient_id %></p>
    <p><strong>Age:</strong> <%= @patient.age %></p>
    <p><strong>Gender:</strong> <%= @patient.gender %></p>
    <p><strong>Tumor Type:</strong> <%= @patient.tumor_type %></p>
    <p><strong>Tumor Grade:</strong> <%= @patient.tumor_grade %></p>
    <p><strong>Tumor Location:</strong> <%= @patient.tumor_location %></p>
    <p><strong>Treatment:</strong> <%= @patient.treatment %></p>
    <p><strong>Treatment Outcome:</strong> <%= @patient.treatment_outcome %></p>
    <p><strong>Time to Recurrence (months):</strong> <%= @patient.time_to_recurrence %></p>
    <p><strong>Recurrence Site:</strong> <%= @patient.recurrence_site %></p>
    <p><strong>Survival Time (months):</strong> <%= @patient.survival_time %></p>

    <%= link_to 'Volver al Listado', patients_path, class: 'btn btn-secondary' %>

  </div>
</div>